# Generated by Django 5.0.4 on 2024-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_discount_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discounts',
        ),
    ]
