# Generated by Django 5.0.4 on 2024-05-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_discount_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
