# Generated by Django 5.0.4 on 2024-05-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
