# Generated by Django 5.0.4 on 2024-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_remove_order_total_amount_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
